Feature info s
RasmusJensen1/P2 pull request #11
Opened 2024-04-11 14:16 UTC by RasmusJensen1

Smid comments på ting der skal fixes

2024-04-11 17:29 UTC, EmilLykke commented on public/images/image1.png
Bro...

2024-04-11 17:30 UTC, EmilLykke commented on public/stylesheets/info.css
> +    min-height: 100vh;
er det ikke lidt sus at tilføje den her til body? Vi har jo allerede en body i main css filen. 
Synes ikke der skal være nogen styling på body

2024-04-11 17:31 UTC, EmilLykke commented on public/stylesheets/info.css
> +body {
Og så tror jeg ikke det er nødvendigt at lave styling til tingene 2 gange

2024-04-11 17:31 UTC, EmilLykke commented on views/info.ejs
> +<!--Sebach was here-->
Fjern den her comment

2024-04-11 17:31 UTC, EmilLykke commented on views/info.ejs
> +      <li>- When making a budget, you can add expenses by clicking on the + button
Fjern -

2024-04-11 17:32 UTC, EmilLykke commented on views/info.ejs
> +    </ul>
Har du testet din side? Du lukker en ul uden at have startet den

2024-04-11 17:32 UTC, EmilLykke commented on views/info.ejs
> +  </ul>
samme her

2024-04-11 17:32 UTC, EmilLykke requested changes
Fix

2024-04-12 11:54 UTC, RasmusJensen1 commented
PR comments fixed

2024-04-12 11:54 UTC, closed without merging