Feature/downloadbudget
RasmusJensen1/P2 pull request #34
Opened 2024-04-19 09:20 UTC by RasmusJensen1

2024-04-19 10:33 UTC, EmilLykke commented on views/budgetinstance.ejs
> +    <h3 id="download-text">Download</h3>
Hvorfor lægger du ikke bare den her H3 ind i samme div som du allerede har stylet til at være i højre nederste hjørne? Så slipper du for at style den. 
Desuden brude den div der har download image class også have `butt` og `butt-primary`

2024-04-19 10:34 UTC, EmilLykke commented on public/javascript/mainPageChart.js
> +// Download JSON file by clicking on the download icon or download text
Hvorfor står den her her? Den står bare uden noget. Ligner at det er chat der har lavet det...

2024-04-19 10:34 UTC, EmilLykke requested changes
fix

2024-04-22 07:09 UTC, RasmusJensen1 commented on public/javascript/mainPageChart.js
> +// Download JSON file by clicking on the download icon or download text
Det ikke chat - Det er så man ved hvad koden "overordnet" gør

2024-04-22 07:46 UTC, RasmusJensen1 commented on views/budgetinstance.ejs
> +    <h3 id="download-text">Download</h3>
fixet

2024-04-22 08:50 UTC, EmilLykke approved these changes
nice

2024-04-22 08:51 UTC, merged