delete expense og save
RasmusJensen1/P2 pull request #37
Opened 2024-04-21 11:16 UTC by Alb9ert

2024-04-21 11:16 UTC, Alb9ert commented on public/javascript/mainPage.js
> +        delete_image.setAttribute("id", expense.name + "-delete");
skal nok fjerne id tænker jeg det ligemeget

2024-04-21 11:33 UTC, EmilLykke requested changes
Almost nice

2024-04-21 11:33 UTC, EmilLykke commented on controllers/budgetinstanceController.js
> +});
```suggestion
exports.budget_instance_post = asyncHandler(async (req, res, next) => {
  const budget = req.body;
  const hasUser = req.cookies.user_cookie;
  if(!hasUser) {
    return res.status(401).send("Unauthorized");
  }
  const user = JSON.parse(atob(decodeURIComponent(hasUser)));


  try {
    // Update the existing budget document if it exists
    await Budget.findOneAndUpdate(
      { _id: budget._id, userId: user.id},
      { 
        ...budget
      },
      { new: true, runValidators: true}
    );
  } catch (error) {
    console.error("Error updating budget:", error);
  }
  
});


```

2024-04-21 11:35 UTC, EmilLykke commented on public/stylesheets/budgetinstance.css
> +  margin-right: 257px;
huh

2024-04-21 11:35 UTC, EmilLykke commented on views/budgetinstance.ejs
> +      <form action="/my-budgets">
Hvorfor bliver vi redirectet til den her side?

2024-04-21 11:36 UTC, EmilLykke commented on controllers/budgetinstanceController.js
> +  } catch (error) {
Desuden må der gerne være bedre error handling så brugern ved om den rent faktisk er blevet gemt ordentligt

2024-04-21 11:36 UTC, EmilLykke requested changes
ff

2024-04-22 07:40 UTC, EmilLykke approved these changes
gj

2024-04-22 07:40 UTC, merged