feature/login unit test
RasmusJensen1/P2 pull request #56
Opened 2024-04-26 11:49 UTC by Alb9ert

2024-04-26 11:56 UTC, OliverKjaer approved these changes
good

2024-04-26 11:57 UTC, AleksandarDzambas approved these changes

2024-04-27 03:09 UTC, EmilLykke commented on controllers/userController.js
> +      res.status(400).send("Incorrect user").render("login", {
Du har tilføjet det her men du har ikke en test til det?

2024-04-27 03:10 UTC, EmilLykke commented on controllers/userController.test.js
> +    const user = await User.findOne({ username: 'testuser' });
måske både kig efter username og password

2024-04-27 03:11 UTC, EmilLykke commented on controllers/userController.js
> +      res.status(400).send("Incorrect user").render("login", {
Du har en send her men du tjekker ikke om response indeholder den besked der i din test?

2024-04-27 03:13 UTC, EmilLykke commented on controllers/userController.test.js
> +function getCookie(name, cookie) {
Ralle har den samme function i hans kode, så jeg ville foreslå at vi laver en fil til den hvor begge steder kan impotere den fra. Det gør den person der får merget sidst

2024-04-27 03:18 UTC, EmilLykke requested changes
fix

2024-04-28 18:03 UTC, merged