Feature/testing sign up
RasmusJensen1/P2 pull request #57
Opened 2024-04-26 12:29 UTC by RasmusJensen1

2024-04-26 12:30 UTC, Alb9ert commented on controllers/userController.test.js
> +  // Testing if user is added to database when signing up with new username and password and it redirects to login page
User should be added to database <= ændre til

2024-04-26 12:32 UTC, Alb9ert commented on controllers/userController.test.js
> +    const newPassword = makeid(10);
makeId (med stort i) ændre her og nede i funktion deffenition

2024-04-26 12:33 UTC, Alb9ert commented on controllers/userController.test.js
> +    result += characters.charAt(Math.floor(Math.random() * charactersLength));
const istedet for var i alle undtagen i for loop der skal det være let

2024-04-26 12:34 UTC, Alb9ert commented on controllers/userController.test.js
> +    const newPassword = makeid(10);
FAKTISK KALD DEN randomString istedet

2024-04-26 12:34 UTC, Alb9ert commented on controllers/userController.test.js
> +
funktion navn

2024-04-26 12:35 UTC, Alb9ert commented on controllers/userController.test.js
> +  // NewPassword and ReapeatPassword doesnt match
does not match*

2024-04-26 12:36 UTC, Alb9ert commented on controllers/userController.test.js
> +  test("Should respond with status code 400 because passwords does not match", async () => {
do not match*

2024-04-26 12:36 UTC, Alb9ert commented on controllers/userController.test.js
> +}
slet har jeg i min pr :)

2024-04-26 12:37 UTC, RasmusJensen1 commented on controllers/userController.test.js
> +}
rip

2024-04-26 12:43 UTC, Alb9ert approved these changes

2024-04-26 12:44 UTC, OliverKjaer approved these changes
klasse

2024-04-27 03:17 UTC, EmilLykke commented on controllers/userController.test.js
> +  test("Should respond with status code 400 because password is too short", async () => {
Til alle de her error checks ville det være nice at i også tjekke om den teks der kom tilbage indholdte error beskeden som vi forventer.

2024-04-27 03:17 UTC, EmilLykke commented on controllers/userController.test.js
> +  test("Should respond with status code 400 because password is too short", async () => {
Ellere rettere. Det skal checkes

2024-04-27 03:18 UTC, EmilLykke commented on controllers/userController.test.js
> +function generateString(length) {
Ligsom med getCookie, skal den her også i sin egen fil som gør den tilgængelig for andre filer

2024-04-27 03:18 UTC, EmilLykke requested changes
f

2024-04-28 18:15 UTC, merged