Sign up
RasmusJensen1/P2 pull request #7
Opened 2024-04-08 12:10 UTC by Alb9ert

2024-04-09 04:26 UTC, EmilLykke commented on public/stylesheets/login.css
> +    margin-left: 100px;
top left gang

2024-04-09 04:27 UTC, EmilLykke commented on routes/index.js
> +// Post signup information
Skriv kommentaren magen til de andre

2024-04-09 04:28 UTC, EmilLykke commented on views/login.ejs
> +          <input type="text" class="form-control" name="email" required="" autofocus="" />
`required=""` `autofocus=""` ??

2024-04-09 04:28 UTC, EmilLykke commented on views/login.ejs
> +            <input type="password" class="form-control" name="password" required="" />
samme her

2024-04-09 04:29 UTC, EmilLykke commented on views/login.ejs
> +        <input type="text" class="form-control" name="newEmail" required="" autofocus="" />
samme for resten også

2024-04-09 04:32 UTC, EmilLykke commented on controllers/userController.js
> +// // Tjek for at se om det virker
Fjern de her comments?

2024-04-09 04:33 UTC, EmilLykke commented on controllers/userController.js
> +exports.login_post = asyncHandler(async (req, res, next) => {
tilføj det her til projektet:

https://github.com/EmilLykke/iwp-aau/blob/master/locallibrary/controllers/bookController.js#L7

så i også kan implementere det her:
https://github.com/EmilLykke/iwp-aau/blob/master/locallibrary/controllers/bookController.js#L102-L115

2024-04-09 04:34 UTC, EmilLykke commented on controllers/userController.js
> +  console.log(newData);
Fjern `console.log` når i er done. Også fra de andre render functioner

2024-04-09 04:37 UTC, EmilLykke commented on app.js
> +var bodyParser = require("body-parser"); // require body form data???? (til email og pasword)
Hvis i implementere de der ting fra local llibary som jeg har linket til længere nede tror jeg det her kan fjernes

2024-04-09 04:37 UTC, EmilLykke commented on app.js
> +var bodyParser = require("body-parser"); // require body form data???? (til email og pasword)
altså uninstalles

2024-04-09 04:39 UTC, EmilLykke requested changes
Godt arbejde gutter. Var det ikke Oliver der skulle lave sign up og log in?
Anyways der er lige nogle rettleser så det bliver 100%, men pisse godt at i kunne få det op at køre!

2024-04-10 12:59 UTC, EmilLykke commented on app.js
> +var createError = require("http-errors");
Ændre alle `var` tilbage til `const`

2024-04-10 13:00 UTC, EmilLykke commented on controllers/indexController.js
> +const { body, validationResult } = require("express-validator");
Hvis vi ikke bruger det på den her side skal vi ikke impotere det.

2024-04-10 13:06 UTC, EmilLykke commented on controllers/userController.js
> +
Fjern mellemrum her. Har du droppet error handling her?

2024-04-10 13:08 UTC, EmilLykke commented on controllers/userController.js
> +        title: "Sign up",
Title her også med småt og evt. med `sign_up`

2024-04-10 13:09 UTC, EmilLykke commented on models/user.model.js
> +    minlength: 8,
Hvorfor i?

2024-04-10 13:10 UTC, EmilLykke commented on public/javascripts/passwordMatch.js
> +// document
Vi har droppet det her eller hvad?
I så fald slet filen

2024-04-10 13:10 UTC, EmilLykke commented on routes/index.js
> +// Post signup information
Den her gælder stadig

2024-04-10 13:11 UTC, EmilLykke commented on views/layout.ejs
> +  <head>
Merge main ind i

2024-04-10 13:11 UTC, EmilLykke commented on views/layout.ejs
> +    <% if(title == 'Login' || title == 'Sign up') { %>
Det ligner ikke scriptet bliver brugt?

2024-04-10 13:12 UTC, EmilLykke commented on controllers/userController.js
> +const User = require("../models/user.model");
Vi bruger ikke den her endnu?

2024-04-10 13:13 UTC, EmilLykke requested changes
Ændre nolge af tingene

2024-04-10 13:32 UTC, OliverKjaer commented on views/login.ejs
> +            <button class="butt" id="login-btn" name="Submit" value="Login" type="Submit">Create
Behøves ikke value!

2024-04-11 08:31 UTC, Alb9ert commented on controllers/userController.js
> +    title: "Login",
På den side der render den titlen så hvis ikke det er stort kommer det til at stå småt på siden. Det jo med if statement inden på ejs

2024-04-11 08:31 UTC, Alb9ert commented on controllers/userController.js
> +
ikke lavet endnu

2024-04-11 08:32 UTC, Alb9ert commented on controllers/userController.js
> +
skal først forbinde til databasen så man kan se om username og password er i databasen

2024-04-11 08:32 UTC, Alb9ert commented on controllers/userController.js
> +        title: "Sign up",
samme som før med if statement i ejs render titlen som header

2024-04-11 08:35 UTC, Alb9ert commented on public/stylesheets/login.css
> +    margin-left: 100px;
ser fint ud når jeg trækker siden så er den stadig formateret korrekt

2024-04-11 10:45 UTC, EmilLykke commented on controllers/userController.js
> +    title: "Login",
Så skal det være med stort på alle sider, for at vi holder det consistent

2024-04-11 10:46 UTC, EmilLykke commented on controllers/userController.js
> +        title: "Sign up",
Samme som før, så skal alle sider have det med stort

2024-04-11 10:46 UTC, EmilLykke commented on models/user.model.js
> +    minlength: 8,
nej vi blev enige om 10. Så blev i enige uden my

2024-04-11 10:46 UTC, EmilLykke commented on controllers/userController.js
> +const User = require("../models/user.model");
Okay men kommer det ind i det her PR eller et andet?

2024-04-11 10:47 UTC, EmilLykke commented on views/layout.ejs
> +    <% break; case 'my_budgets': %>
Ændre til stort på alle sider. husk her også

2024-04-11 10:47 UTC, EmilLykke requested changes
små ting, ser meget godt ud ellers

2024-04-11 10:56 UTC, EmilLykke approved these changes
nice

2024-04-11 10:56 UTC, EmilLykke commented on controllers/budgetinstanceController.js
> +    title: "Budget_instance",
Kan være vi skal fjerne `_` i fremtiden, men det er nice for nu

2024-04-11 11:00 UTC, AleksandarDzambas approved these changes
Ser fint ud, kunne ikke se større fejl umiddelbart

2024-04-11 11:01 UTC, merged